services:
  seq:
    image: datalust/seq:2024
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"
    networks:
      - network

  web:
    build:
      context: ./services/SportHub-web
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AUTH_TRUST_HOST: true
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_YANDEX_ID: ${AUTH_YANDEX_ID}
      AUTH_YANDEX_SECRET: ${AUTH_YANDEX_SECRET}
    ports:
      - "3000:3000"
    networks:
      - network

  parser:
    build:
      context: ./services/SportHub-parser
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PDF_FILE_URL: https://www.minsport.gov.ru/activity/government-regulation/edinyj-kalendarnyj-plan/
    ports:
      - "8000:8000"
    depends_on:
      - web
    networks:
      - network

networks:
  network: