services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1488:1488"
    networks:
      - my_network

  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    networks:
      - my_network
  
  web:
    image: web
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - AUTH_TRUST_HOST=true
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - my_network
  
  notification:
    image: notification
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - seq
    restart: always
    environment:
        - ASPNETCORE_ENVIRONMENT=Docker
        - SMTP_SERVER=smtp.gmail.com
        - SMTP_PORT=587
        - SMTP_USERNAME=minoddein.ezz@gmail.com
        - SMTP_PASSWORD=urlruiukmyuarruj
    ports:
      - "8080:8080"
    networks:
      - my_network
      
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 3004:80
    networks:
      - my_network

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "notifications"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "345890"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    networks:
      - my_network

volumes:
  postgres-data:

networks:
  my_network: